In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('Cleaned-P&P data.csv')
df.head()

class                                               desc     inc_num  \
0     P  good afternoon,\r\n\r\nthis customer is being ...  INC0809260   
1     R  please can you remove the delivery pass be rem...  INC0808628   
2     O  please set (acustrss ) to 1 so account holder ...  INC0807303   
3     R  please can the delivery pass be removed from t...  INC0807253   
4     P  customer: d4957244\r\nwebsite:jd williams, mai...  INC0806836   

                                           short_des  
0                                           y2684992  
1  delivery pass needs removing on staff accounts...  
2                                           g7121564  
3  delivery pass needs removing on staff accounts...  
4                customer being charged for delivery

In [2]:
blanks = []  # start with an empty list`

for i,c,d,inc,sd in df.itertuples():  # iterate over the DataFrame
        if c == 'O' or c=='E':         # test 'review' for whitespace
            blanks.append(i)     # add matching index numbers to the list
df.drop(blanks, inplace=True)

In [3]:
df["desc"] = df["short_des"] + '. ' + df["desc"]
len(df)

244

In [4]:
from sklearn.model_selection import train_test_split

X = df["desc"]
y = df['class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)


In [5]:

X_train.shape, X_test.shape, y_train.shape, y_test.shape
X_train=X_train.values.reshape((195,1))
y_train=y_train.values.reshape((195,1))

In [6]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

# Naïve Bayes:
text_clf_nb = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', MultinomialNB()),
])

# Linear SVC:
text_clf_lsvc = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', LinearSVC()),
])

In [7]:

X_train = np.array(X_train).tolist()
y_train = np.array(y_train).tolist()

In [8]:
X_train = list(map(''.join, X_train)) 
y_train = list(map(''.join, y_train)) 

In [9]:
text_clf_nb.fit(X_train, y_train)

Pipeline(memory=None,
     steps=[('tfidf', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,...rue,
        vocabulary=None)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [10]:
predictions = text_clf_nb.predict(X_test)

In [11]:
# Report the confusion matrix
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[31  0]
 [ 1 17]]


In [12]:

print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

           P       0.97      1.00      0.98        31
           R       1.00      0.94      0.97        18

   micro avg       0.98      0.98      0.98        49
   macro avg       0.98      0.97      0.98        49
weighted avg       0.98      0.98      0.98        49



In [13]:
print(metrics.accuracy_score(y_test,predictions))

0.9795918367346939


In [19]:
incident = 'can you please cancel the following accounts from getting free delivery pass. \na00012345\na12345678 \nwebsite : simply \norder number : 1168655 \nbrowser : google chrome'
#incident = ''
print(text_clf_nb.predict([incident]))
print(incident)
print(text_clf_nb.predict_proba([incident]))

['P']
can you please cancel the following accounts from getting free delivery pass. 
a00012345
a12345678 
website : simply 
order number : 1168655 
browser : google chrome
[[0.56439514 0.43560486]]


In [20]:
from sklearn.model_selection import cross_val_score
cross_val_score(text_clf_nb, X, y, cv = 10)

array([1.        , 1.        , 1.        , 0.96      , 0.96      ,
       1.        , 1.        , 1.        , 1.        , 0.82608696])

In [26]:
X_test[-5:]

203    customer being charged for standard delivery -...
69     customer is being charged for delivery even if...
174    delivery subscription not working. please acti...
40     delivery subscription issue. fault : david cal...
202    customer wishes to cancel annual delivery. t39...
Name: desc, dtype: object

In [25]:
text_clf_nb.predict_proba(X_test[-5:])

array([[0.96592399, 0.03407601],
       [0.98095241, 0.01904759],
       [0.95750529, 0.04249471],
       [0.9945785 , 0.0054215 ],
       [0.18799341, 0.81200659]])

In [88]:
arr = text_clf_nb.predict_proba(X_test[:5])

Sum of all elements in given list:  0.9999999999999993
Sum of all elements in given list:  0.9999999999999966
Sum of all elements in given list:  1.0000000000000004
Sum of all elements in given list:  0.9999999999999989
Sum of all elements in given list:  1.0000000000000013


In [103]:
from sklearn.feature_selection import chi2
import numpy as np
N = 2
for Product, category_id in sorted(category_to_id.items()):
  features_chi2 = chi2(features, labels == category_id)
  indices = np.argsort(features_chi2[0])
  feature_names = np.array(tfidf.get_feature_names())[indices]
  unigrams = [v for v in feature_names if len(v.split(' ')) == 1]
  bigrams = [v for v in feature_names if len(v.split(' ')) == 2]
  print("# '{}':".format(Product))
  print("  . Most correlated unigrams:\n. {}".format('\n. '.join(unigrams[-N:])))
  print("  . Most correlated bigrams:\n. {}".format('\n. '.join(bigrams[-N:])))

NameError: name 'category_to_id' is not defined

KeyError: "['class' 'desc'] not in index"